import { Button,PageHeader,Descriptions,Menu,Icon,Switch,Statistic ,Row ,Col ,Carousel,message,FormModel,Input,Select,DatePicker,Tooltip,
    Layout,Divider,Card,Space,Slider,Dropdown,Collapse,Timeline,Steps,Result,Tabs,Drawer,Empty,Upload,Modal,TimePicker,InputNumber,Table
} from 'ant-design-vue';
    
import Vue from 'vue'
    

export default function () {
    Vue.config.productionTip = false
    Vue.component(Button.name, Button)
    Vue.component(Button.Group.name, Button.Group)
    Vue.component(PageHeader.name,PageHeader)
    Vue.component(Descriptions.name,Descriptions)
    Vue.component(Descriptions.Item.name,Descriptions.Item)
    Vue.component(Icon.name,Icon)
    Vue.component(Menu.name,Menu )
    Vue.component(Menu.Item.name, Menu.Item)
    Vue.component(Menu.SubMenu.name, Menu.SubMenu)
    Vue.component(Switch.name,Switch)
    Vue.component(Statistic.name,Statistic )
    Vue.component(Row.name,Row )
    Vue.component(Col.name,Col )
    Vue.component(Carousel.name,Carousel)
    Vue.component(FormModel.name,FormModel)
    Vue.component(FormModel.Item.name,FormModel.Item)
    Vue.component(Input.name,Input)
    Vue.component(Input.Password.name,Input.Password)
    Vue.component(Input.Group.name,Input.Group)
    Vue.component(Select.name,Select )
    Vue.component(Select.Option.name,Select.Option )
    Vue.component(DatePicker.name,DatePicker)
    Vue.component(DatePicker.RangePicker.name,DatePicker.RangePicker)
    Vue.component(Tooltip.name,Tooltip)
    Vue.component(Layout.name,Layout)
    Vue.component(Layout.Sider.name,Layout.Sider)
    Vue.component(Layout.Content.name,Layout.Content)
    Vue.component(Layout.Footer.name,Layout.Footer)
    Vue.component(Divider.name,Divider)
    Vue.component(Card.name,Card)
    Vue.component(Card.Meta.name,Card.Meta)
    Vue.component(Card.Grid.name,Card.Grid)
    Vue.component(Space.name,Space)
    Vue.component(Slider.name,Slider)
    Vue.component(Dropdown.name,Dropdown)
    Vue.component(Collapse.name,Collapse)
    Vue.component(Collapse.Panel.name,Collapse.Panel)
    Vue.component(Timeline.name,Timeline)
    Vue.component(Timeline.Item.name,Timeline.Item)
    Vue.component(Steps.name,Steps)
    Vue.component(Steps.Step.name,Steps.Step)
    Vue.component(Result.name,Result)
    Vue.component(Tabs.name,Tabs)
    Vue.component(Tabs.TabPane.name,Tabs.TabPane)
    Vue.component(Drawer.name,Drawer)
    Vue.component(Empty.name,Empty)
    Vue.component(Upload.name,Upload)
    Vue.component(TimePicker.name,TimePicker)
    Vue.component(InputNumber.name,InputNumber)
    Vue.component(Table.name,Table)
    Vue.prototype.$message = message;
    Vue.use(Modal)
}